### ISSUE TITLE
mem check error

### ISSUE THREAD

**Issue by Ahmedfouad** [dduenasd/check_tomcat.py#1]
./check_tomcat.py -H 127.0.0.1 -p 80  -u user -a pass -m mem -w 50 -c 70

Traceback (most recent call last):
  File "./check_tomcat.py", line 430, in <module>
    output="Used memory "+sizeof_fmt(used_memory)+" of "+sizeof_fmt(max_memory)+"(%0.2f%%)" %(percent_used_memory)
  File "./check_tomcat.py", line 177, in sizeof_fmt
    return format_string.format(quotient, unit)
ValueError: zero length field name in format

**Comment by dduenasd** [comment]
What is the tomcat version you are monitorized?

**Comment by viniciusfs** [comment]
Which python version are you running? I found this error while running check_tomcat.py on old python 2.6.7 version. I created a new pull request with function format_string fixed to work on old python versions: https://github.com/dduenasd/check_tomcat.py/pull/2

**Comment by dduenasd** [comment]
Thanks, the version of my python is 2.7.3
